# Data Analytics - Exercise 4

Assignments must be submitted as an HTML file, showing both the contents of the code cells and the outputs. You can get the notebook as an HTML file by selecting File -> Download as -> HTML. The answers to the tasks can be done in one or more code cells.

**Student's name**: Jayani Kothalawala

**Student number**: AD9680

## Merging Data - Part 1

Read the data on cyber attacks from 2022 into the DataFrame df_2022 and the data on cyber attacks from 2023 into the DataFrame df_2023.

a) Merge the data from 2023 and 2022 into a single DataFrame df_2022_2023. Print the length of the merged DataFrame.

b) In situations where data is divided into different files by time period, the files often contain some "extra" data. For example, data divided by year may include timestamps and their information from the last day of the previous year. Thus, when merging data from multiple years, these rows appear multiple times in the data. Investigate how many duplicate/overlapping rows resulted in the DataFrame df_2022_2023 from the merge.

c) Next, we will remove duplicate rows and some NaN values. First, study the Pandas documentation for functions to remove duplicate rows and NaN values. Which parameter do you use to apply the modification to the entire DataFrame, rather than returning just a view?

d) Remove duplicate rows and rows where both 'Source Network' and 'Destination Network' information are NaN (not just one, but both are NaN).

e) Sort the data by the "Timestamp" column with the oldest data first and reindex the DataFrame. (The first index of the result should be 0 and the value in the Timestamp column should be 2022-01-01 16:29:59.)

Scoring: 2.5 p

In [74]:
import pandas as pd

df_2022 = pd.read_csv('https://student.labranet.jamk.fi/~ajota/Datasets/cybersecurity_attacks_2022.csv', index_col=0)
df_2023 = pd.read_csv('https://student.labranet.jamk.fi/~ajota/Datasets/cybersecurity_attacks_2023_v2.csv', index_col=0)

In [86]:
# Cell / answer 1.1 a) - merging of data
# Print the length/number of rows of the merged DataFrame and copy it into the Moodle answer field.



df_2022_2023 = pd.concat([df_2022, df_2023], ignore_index=True)

len(df_2022_2023)

2369

In [87]:
# Cell / Answer 1.1 b) - number of duplicate rows
# Print the number of duplicate rows and copy the count into the Moodle answer field. (From the Pandas documentation: '...the first occurrence is set on False and all others on True.' We will use the default settings for this task.)
df_2022_2023.duplicated().sum()

np.int64(3)

In [ ]:
# Cell / Answer 1.1 c)
# Study the Pandas documentation / course materials to find the parameter that applies the modification to the original DataFrame. Write the parameter name in the Moodle answer field.
# inplace=True

In [89]:
# Cell / Answer 1.1 d) - dropping duplicates and NaN rows
# Copy the number of rows in the modified DataFrame into the Moodle answer field.
df_2022_2023.drop_duplicates(inplace=True)
df_2022_2023.dropna(
    subset=["Source Network", "Destination Network"],
    how="all",
    inplace=True
)
df_2022_2023 
len(df_2022_2023)

1779

In [90]:
# Cell / Answer 1.1 e) - reindexing and sorting data
# Copy the 'Source IP Address' information from the last row of the sorted DataFrame into the Moodle answer field.

df_2022_2023 = df_2022_2023.sort_values(by="Timestamp")
df_2022_2023.reset_index(drop=True, inplace=True)
df_2022_2023.iloc[-1]["Source IP Address"]

'130.231.62.201'

## Merging Data - Part 2

Add information about the continent and country name of IP addresses (continent_name and country_name data from the DataFrame df_geo) to the DataFrame df_2022_2023 modified in the previous exercise.

Add information for both the source IP and the destination IP. The goal is to know the traffic flow from source to destination.
The DataFrames df_2023 and df_2022 already have columns Source Network and Destination Network, which you can use for merging.
If the merge results in duplicate columns, drop these.
Name the new columns as follows: Source IP Continent, Source IP Country, Destination IP Continent, and Destination IP Country.
Print the "Timestamp", "Source IP Address", "Destination IP Address", "Source Network", "Destination Network", "Source IP Continent", "Source IP Country", "Destination IP Continent", "Destination IP Country" information.

Below is an example of the desired outcome.

Scoring: 1 p

![malli](https://student.labranet.jamk.fi/~ajota/Data-analytics/images/lopputulos_cybersecurity_attacks_df_2022_2023.png)

In [80]:
df_geo = pd.read_csv('https://student.labranet.jamk.fi/~ajota/Datasets/geoip2-ipv4.csv')

In [91]:
# Cell / Answer 1.2
# Copy the country information from the last row of the 'Destination IP Country' column into the Moodle answer field.
geo = df_geo[["network", "continent_name", "country_name"]]
df_2022_2023 = df_2022_2023.merge(
    geo,
    left_on="Source Network",
    right_on="network",
    how="left"
)
df_2022_2023.rename(columns={
    "continent_name": "Source IP Continent",
    "country_name": "Source IP Country"
}, inplace=True)

df_2022_2023.drop(columns=["network"], inplace=True)
df_2022_2023 = df_2022_2023.merge(
    geo,
    left_on="Destination Network",
    right_on="network",
    how="left"
)
df_2022_2023.rename(columns={
    "continent_name": "Destination IP Continent",
    "country_name": "Destination IP Country"
}, inplace=True)

df_2022_2023.drop(columns=["network"], inplace=True)
df_2022_2023.drop_duplicates(inplace=True)
df_2022_2023 = pd.DataFrame(df_2022_2023[["Timestamp","Source IP Address","Destination IP Address","Source Network","Destination Network","Source IP Continent","Source IP Country","Destination IP Continent","Destination IP Country"]])
df_2022_2023.iloc[-1]["Destination IP Country"]

'Switzerland'

## Datan ryhmittely

Grouping Data
We will group the data in the DataFrame df_2022_2023 compiled in the previous sections. If you were unable to complete the previous sections, you can read the data to be grouped from the URL https://student.labranet.jamk.fi/~ajota/Datasets/cybersecurity_attacks_2022_2023.csv.

a) Investigate how many times each continent appears in the data when grouped by the source IP address. (Group the data by the "Source IP Continent" column. Use a built-in method to determine the count.)

b) Group the data first by the destination IP address continent (Destination IP Continent) and then by the attack type (Attack Type) in descending order. Which continent and attack type are first in the grouping?

c) Next, group the data first by the source IP address continent (Source IP Continent) and then by the source IP address country (Source IP Country). Sort the values first by continent in ascending order and secondarily by the source IP address (Source IP Address) in descending order. What are the continent and country details on the last row of the table? Below is an example of the first rows for part c).

Scoring: 1.5 p

![malli](https://student.labranet.jamk.fi/~ajota/Data-analytics/images/malli_datan_ryhmittelya_ja_jarjestamista.png)

In [99]:
df_2022_2023 = pd.read_csv('https://student.labranet.jamk.fi/~ajota/Datasets/cybersecurity_attacks_2022_2023.csv', index_col=0)
df_2022_2023

,Timestamp,Source IP Address,Destination IP Address,Source Port,Destination Port,Protocol,Packet Length,Packet Type,Traffic Type,Payload Data,...,Proxy Information,Firewall Logs,IDS/IPS Alerts,Log Source,Source Network,Destination Network,Source IP Continent,Source IP Country,Destination IP Continent,Destination IP Country
0,2022-01-01 16:29:59,47.110.78.44,93.82.7.181,10498,35012,TCP,1114,Data,FTP,Ipsa consectetur nulla molestiae.\nEum dolor n...,...,NaN,NaN,NaN,Server,NaN,93.82.0.0/15,NaN,NaN,Europe,Austria
1,2022-01-02 06:41:40,150.237.223.140,195.137.227.149,19241,50829,TCP,869,Data,HTTP,Dolores suscipit eaque consequatur. Distinctio...,...,218.136.32.18,NaN,Alert Data,Firewall,150.237.0.0/16,195.137.226.0/23,Europe,United Kingdom,Europe,Ukraine
2,2022-01-03 00:02:21,129.4.179.142,194.169.247.114,44455,46510,TCP,171,Control,FTP,Harum cupiditate deserunt iusto. Asperiores un...,...,150.44.249.211,NaN,NaN,Server,NaN,194.169.247.0/24,NaN,NaN,Europe,Russia
3,2022-01-03 09:15:39,37.135.46.119,98.206.212.30,40729,65426,UDP,1091,Control,FTP,Quo nobis molestias esse iste ea quae. Dolorem...,...,46.207.16.120,Log Data,Alert Data,Server,37.132.0.0/14,NaN,Europe,Spain,NaN,NaN
4,2022-01-03 18:04:06,143.233.181.85,107.146.5.56,62176,57985,ICMP,870,Control,FTP,Architecto delectus magnam nemo ipsam consequu...,...,12.251.225.181,Log Data,NaN,Firewall,143.233.0.0/16,NaN,Europe,Greece,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1774,2023-10-10 06:46:13,21.48.3.230,197.89.113.74,30332,57869,TCP,1447,Data,FTP,Soluta quo in repellendus. Esse nisi sit nobis...,...,205.177.9.232,Log Data,NaN,Server,NaN,197.64.0.0/11,NaN,NaN,Africa,South Africa
1775,2023-10-10 15:11:34,111.103.192.212,72.99.102.231,8696,4448,ICMP,885,Control,FTP,Repellendus autem error corrupti fuga. Totam o...,...,103.152.169.20,Log Data,NaN,Firewall,111.96.0.0/12,NaN,Asia,Japan,NaN,NaN
1776,2023-10-11 02:42:38,109.202.200.248,34.41.151.160,42323,30691,ICMP,537,Data,HTTP,Sapiente perferendis eaque sapiente vero.\nVen...,...,NaN,NaN,Alert Data,Firewall,109.202.192.0/19,NaN,Europe,Switzerland,NaN,NaN
1777,2023-10-11 06:42:19,84.187.46.81,13.165.19.36,62842,12691,UDP,1269,Control,FTP,Esse voluptatibus natus accusantium veritatis ...,...,77.39.183.35,NaN,Alert Data,Firewall,84.128.0.0/10,NaN,Europe,Germany,NaN,NaN
1778,2023-10-11 12:29:23,130.231.62.201,137.34.162.176,60626,52879,UDP,392,Control,DNS,Excepturi ad asperiores repudiandae. Fugit duc...,...,NaN,Log Data,NaN,Server,130.230.0.0/15,137.34.0.0/16,Europe,Finland,Europe,Switzerland

In [93]:
# This will be checked in Moodle in multiple parts:
# Cell / Answer 1.3 a) - Africa
# Cell / Answer 1.3 a) - Asia
# Cell / Answer 1.3 a) - Europe
df = df_2022_2023.groupby(["Source IP Continent"]).count()
df

,Timestamp,Source IP Address,Destination IP Address,Source Network,Destination Network,Source IP Country,Destination IP Continent,Destination IP Country
Source IP Continent,,,,,,,,
Africa,48,48,48,48,19,48,19,19
Asia,534,534,534,534,284,534,284,284
Europe,483,483,483,483,262,483,262,262
Oceania,42,42,42,42,25,42,25,25
South America,89,89,89,89,54,89,54,54

In [126]:
# This will be checked in Moodle in two parts:
# Cell / Answer 1.3 b) - continent
# Cell / Answer 1.3 b) - attack type

# b) Group the data first by the destination IP address continent (Destination IP Continent) and then by the attack type (Attack Type) in descending order. Which continent and attack type are first in the grouping?

df_2022_2023.groupby(
    ["Destination IP Continent", "Attack Type"]
).size().sort_values(ascending=False).head(1)

Destination IP Continent  Attack Type
Asia                      Malware        206
dtype: int64

In [128]:
# Cell / answer 1.3 c)
# This will be checked in Moodle in two parts: answer 1.3 c) - continent
# This will be checked in Moodle in two parts: answer 1.3 c) - country name
# Group by Source IP Continent and Source IP Country
grouped_c = (
    df_2022_2023
    .groupby(["Source IP Continent", "Source IP Country"])
    .count()
)

# Sort by continent ascending and Source IP Address descending
sorted_c = grouped_c.sort_values(
    by=["Source IP Continent", "Source IP Address"],
    ascending=[True, False]
)
sorted_c.tail(1)

,,Timestamp,Source IP Address,Destination IP Address,Source Port,Destination Port,Protocol,Packet Length,Packet Type,Traffic Type,Payload Data,...,Device Information,Network Segment,Proxy Information,Firewall Logs,IDS/IPS Alerts,Log Source,Source Network,Destination Network,Destination IP Continent,Destination IP Country
Source IP Continent,Source IP Country,,,,,,,,,,,,,,,,,,,,,
South America,Paraguay,2,2,2,2,2,2,2,2,2,2,...,2,2,1,0,0,2,2,2,2,2