# Data Analytics - Exercise 2

Please note that the tasks must be submitted to Moodle as an HTML file, **showing both the contents of the code cells and the outputs**. You can get the notebook as an HTML file by selecting File -> Download as -> HTML. You can add comments or Markdown cells in your answers to explain what you have done. Submit the task file in this exercise and check your task using the automatic check in Moodle.

**Student's Name**: Jayani Kothalawala

**Student Number**: AD9680

## Reading data from CSV - URL

a) Read the first 100 rows of the 'cybersecurity_attacks.csv' file from the given URL into a DataFrame.
url = https://student.labranet.jamk.fi/~ajota/Datasets/cybersecurity_attacks.csv
    - Set a parameter to read only the first 100 rows.
    - When reading the data, set the existing index in the file as the index so that the DataFrame does not have an extra "Unnamed: 0" column. (Hint: You can refer to columns by their names or numbers.)
    - Print the last 2 rows of the DataFrame.
    
b) Finally, save the Data Frame's data to a file named "cybersecurity_attacks.csv".

Scoring: 1 p

In [223]:
import pandas as pd
url = "https://student.labranet.jamk.fi/~ajota/Datasets/cybersecurity_attacks.csv"
df = pd.read_csv(url,nrows=100, index_col=0)
df

,Timestamp,Source IP Address,Destination IP Address,Source Port,Destination Port,Protocol,Packet Length,Packet Type,Traffic Type,Payload Data,...,Attack Type,Attack Signature,Action Taken,Severity Level,Device Information,Network Segment,Proxy Information,Firewall Logs,IDS/IPS Alerts,Log Source
0,2023-05-30 06:33:58,103.216.15.12,84.9.164.252,31225,17616,ICMP,503,Data,HTTP,Qui natus odio asperiores nam. Optio nobis ius...,...,Malware,Known Pattern B,Logged,Low,Mozilla/5.0 (compatible; MSIE 8.0; Windows NT ...,Segment A,150.9.97.135,Log Data,NaN,Server
1,2020-08-26 07:08:30,78.199.217.198,66.191.137.154,17245,48166,ICMP,1174,Data,HTTP,Aperiam quos modi officiis veritatis rem. Omni...,...,Malware,Known Pattern A,Blocked,Low,Mozilla/5.0 (compatible; MSIE 8.0; Windows NT ...,Segment B,NaN,Log Data,NaN,Firewall
2,2022-11-13 08:23:25,63.79.210.48,198.219.82.17,16811,53600,UDP,306,Control,HTTP,Perferendis sapiente vitae soluta. Hic delectu...,...,DDoS,Known Pattern B,Ignored,Low,Mozilla/5.0 (compatible; MSIE 9.0; Windows NT ...,Segment C,114.133.48.179,Log Data,Alert Data,Firewall
3,2023-07-02 10:38:46,163.42.196.10,101.228.192.255,20018,32534,UDP,385,Data,HTTP,Totam maxime beatae expedita explicabo porro l...,...,Malware,Known Pattern B,Blocked,Medium,Mozilla/5.0 (Macintosh; PPC Mac OS X 10_11_5; ...,Segment B,NaN,NaN,Alert Data,Firewall
4,2023-07-16 13:11:07,71.166.185.76,189.243.174.238,6131,26646,TCP,1462,Data,DNS,Odit nesciunt dolorem nisi iste iusto. Animi v...,...,DDoS,Known Pattern B,Blocked,Low,Mozilla/5.0 (compatible; MSIE 5.0; Windows NT ...,Segment C,149.6.110.119,NaN,Alert Data,Firewall
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2021-11-24 20:11:15,169.21.155.127,171.38.239.42,47513,9156,UDP,1455,Control,FTP,Rerum maiores sed. Saepe repudiandae dolore sa...,...,DDoS,Known Pattern A,Ignored,High,Mozilla/5.0 (X11; Linux i686; rv:1.9.7.20) Gec...,Segment C,4.152.115.150,NaN,NaN,Firewall
96,2021-12-31 11:46:47,92.192.73.229,72.77.74.9,12215,50585,TCP,640,Control,HTTP,Facere dicta magni corrupti magnam. Aliquam es...,...,Intrusion,Known Pattern A,Blocked,Medium,Mozilla/5.0 (Macintosh; PPC Mac OS X 10_7_1 rv...,Segment C,NaN,Log Data,Alert Data,Server
97,2021-10-25 04:23:15,129.189.216.143,197.202.27.160,19199,27928,ICMP,1178,Data,HTTP,Eaque deserunt nemo ad voluptate. Aliquid rem ...,...,Malware,Known Pattern B,Ignored,High,Mozilla/5.0 (compatible; MSIE 8.0; Windows 95;...,Segment C,57.192.174.154,Log Data,Alert Data,Server
98,2022-04-25 20:26:30,60.223.224.39,218.187.232.192,26123,7023,ICMP,158,Data,HTTP,In repellendus modi ab. Dolore ex sequi perfer...,...,Intrusion,Known Pattern A,Ignored,Medium,Mozilla/5.0 (iPad; CPU iPad OS 9_3_5 like Mac ...,Segment B,45.57.200.181,NaN,NaN,Server
99,2022-03-17 23:44:57,172.26.245.135,21.131.246.181,22345,60531,ICMP,1409,Data,FTP,Blanditiis nulla cupiditate a temporibus at. V...,...,Intrusion,Known Pattern B,Ignored,Low,Mozilla/5.0 (compatible; MSIE 9.0; Windows 98;...,Segment C,169.0.178.199,NaN,Alert Data,Server

In [224]:
# Cell / answer 1.1 a)
# Reading data and parameters when reading it.
# The answer to this task will be checked in Moodle in two parts:
# Exercise 2, assignment 1.1 a) rows
# Exercise 2, assignment 1.1 a) columns
df[-2:]

,Timestamp,Source IP Address,Destination IP Address,Source Port,Destination Port,Protocol,Packet Length,Packet Type,Traffic Type,Payload Data,...,Attack Type,Attack Signature,Action Taken,Severity Level,Device Information,Network Segment,Proxy Information,Firewall Logs,IDS/IPS Alerts,Log Source
98,2022-04-25 20:26:30,60.223.224.39,218.187.232.192,26123,7023,ICMP,158,Data,HTTP,In repellendus modi ab. Dolore ex sequi perfer...,...,Intrusion,Known Pattern A,Ignored,Medium,Mozilla/5.0 (iPad; CPU iPad OS 9_3_5 like Mac ...,Segment B,45.57.200.181,NaN,NaN,Server
99,2022-03-17 23:44:57,172.26.245.135,21.131.246.181,22345,60531,ICMP,1409,Data,FTP,Blanditiis nulla cupiditate a temporibus at. V...,...,Intrusion,Known Pattern B,Ignored,Low,Mozilla/5.0 (compatible; MSIE 9.0; Windows 98;...,Segment C,169.0.178.199,NaN,Alert Data,Server

In [225]:
# Cell / answer 1.1 b)
# Saving Data Frame as csv-file. From this assignment you should copy the whole code to Moodle. In Moodle's automatic assignment checking the name of the dataframe is 'df' and the name of the file to be saved is 'cybersecurity_attacks.csv'.
df.to_csv("cybersecurity_attacks.csv")

## Reading data from CSV - file

Read only the columns listed below from "cybersecurity_attacks.csv" file saved in previous step into a Pandas DataFrame:

- Timestamp
- Source IP Address
- Destination IP Address
- Source Port
- Destination Port
- Protocol

Print the first 2 rows from the DataFrame as an output. Avoid using print()-function, use display or plain name of the DataFrame in the end of the cell instead.

Scoring: 1 p

In [226]:
# Cell / answer 1.2
# Copy the whole output (first two rows) to Moodle's automatic assignment checking.
df = df[["Timestamp","Source IP Address","Destination IP Address","Source Port","Destination Port","Protocol"]]
pd.DataFrame(df)
df.head(2)

,Timestamp,Source IP Address,Destination IP Address,Source Port,Destination Port,Protocol
0,2023-05-30 06:33:58,103.216.15.12,84.9.164.252,31225,17616,ICMP
1,2020-08-26 07:08:30,78.199.217.198,66.191.137.154,17245,48166,ICMP

## Reading and parsing JSON-data

Download the file 'participants.json' from https://student.labranet.jamk.fi/~ajota/Datasets/ to your computer and open it for processing. Parse the JSON containing nested structures so that all key-value pairs in the JSON are in their own columns (the DataFrame columns should be "olympialaiset", "maa", "sijoitus", "painoluokka", "vuosi", "etunimi", "sukunimi", and "ikä").

Finally, print out the DataFrame.

Scoring: 1 p

In [227]:
import json
import pandas as pd

In [228]:
# Cell / answer 1.3
# Copy the whole DataFrame to Moodle's automatic assignment reviewing.
df = json.load(open("participants.json"))

df = pd.json_normalize(df,record_path=["saavutukset"],meta=["etunimi","sukunimi","ikä"])
df

    olympialaiset       maa sijoitus painoluokka  vuosi etunimi  sukunimi ikä
0  Rio De Janeiro  Brasilia    kulta       57 kg   2016   Kaori      Icho  38
1  Rio De Janeiro  Brasilia    kulta       53 kg   2016   Helen  Maroulis  32

## Reading data from a text file

The file 'apache_log.txt' contains Apache server access log data in Combined Log format. The data does not include column headers or an index.

Read the data into a DataFrame from 'https://student.labranet.jamk.fi/~ajota/Datasets/apache_log.txt' so that you get the result shown in the screenshot.

![malli_apache1](https://student.labranet.jamk.fi/~ajota/Data-analytics/images/malli_apache_log_times_gmt_sep.png)

Note that at this stage, the timestamp and GMT information will end up in separate columns, but let's not worry about that for now.

To achieve the final result, investigate/do the following:

Investigate which function you can use to read data from a text file.
Read the data from 'https://student.labranet.jamk.fi/~ajota/Datasets/apache_log.txt'
Investigate which delimiter to use so that the data ends up in separate columns.
Determine which parameter to use to indicate that the data does not include column headers.
Set the column names using the list 'col_names'. You can set all the above in the same function.
Print the first 2 rows of the read DataFrame (do not use the print() function).

col_names = ["Client's IP address", "Identd", "Userid", "Timestamp", "zone", "Request line from the client", "Status code", "Size of content", "Referer", "User-Agent HTTP request header"]

More information about the data can be found here: https://httpd.apache.org/docs/current/logs.html#accesslog.

Scoring: 1 p

In [229]:
# Cell / answer 1.4
# Copy the entire DataFrame (the first 2 rows) into the answer field for Moodle's automatic check.
url = "https://student.labranet.jamk.fi/~ajota/Datasets/apache_log.txt"
col_names = ["Client's IP address", "Identd", "Userid", "Timestamp", "zone", "Request line from the client", "Status code", "Size of content", "Referer", "User-Agent HTTP request header"]
df = pd.read_csv(url, sep=" ", header=None, names=col_names)
df.head(2)

,Client's IP address,Identd,Userid,Timestamp,zone,Request line from the client,Status code,Size of content,Referer,User-Agent HTTP request header
0,109.169.248.247,-,-,[12/Dec/2015:18:25:11,+0100],GET /administrator/ HTTP/1.1,200,4263,-,Mozilla/5.0 (Windows NT 6.0; rv:34.0) Gecko/20...
1,109.169.248.247,-,-,[12/Dec/2015:18:25:11,+0100],POST /administrator/index.php HTTP/1.1,200,4494,http://almhuette-raith.at/administrator/,Mozilla/5.0 (Windows NT 6.0; rv:34.0) Gecko/20...

# Optional exercises

Below are some optional exercises for you to practice different ways of reading data. These exercises do not offer any points and will not be checked.

## From JSON string to DataFrame

The variable "ahtletes" contains athlete data as a JSON string. Create a DataFrame from the data with the columns "etunimi", "sukunimi", "ikä", and "aktiivi". Print the DataFrame.

Note the format in which the data is given and the format required for the DataFrame. Make the necessary changes programmatically, do not manually edit the JSON string.

In [230]:
import json

athletes = '[{"etunimi":"Kaori", "sukunimi":"Icho","ikä":38,"aktiivi":false}, {"etunimi":"Helen","sukunimi":"Maroulis","ikä":32,"aktiivi":true}]'

In [231]:
# Answer

df=pd.DataFrame(json.loads(athletes))
df

  etunimi  sukunimi  ikä  aktiivi
0   Kaori      Icho   38    False
1   Helen  Maroulis   32     True

## REST API

Fetch the IC1 train data from the Digitraffic API for the date 17.10.2023. The URL to use for the query is 'https://rata.digitraffic.fi/api/v1/trains/2023-10-17/1'. The query returns a JSON object containing nested structures. Create a DataFrame from the fetched data, where the timetable rows (timeTableRows) are parsed into rows of the DataFrame. Set the metadata as meta = ['trainNumber', 'departureDate', 'trainType']. Note that the timeTableRows data also includes the train number 'trainNumber', so you need to set the 'record_prefix' parameter in the JSON normalization (e.g., use the prefix 'tTR').

Finally, print the first 5 rows of the DataFrame. The parsed DataFrame should have the columns (tTR_stationShortCode, tTR_stationUICCode, tTR_countryCode, ..., trainNumber, departureDate, trainType).

In [232]:
import requests
import pandas as pd

In [238]:
# Answer
url = "https://rata.digitraffic.fi/api/v1/trains/2023-10-17/1"
data = requests.get(url).json()   # get JSON data

df = pd.json_normalize(data,record_path=["timeTableRows"],meta=["trainNumber","departureDate","trainType"],record_prefix="tTR")      # convert to DataFrame

df = pd.DataFrame(df)
df.head(5)

,tTRstationShortCode,tTRstationUICCode,tTRcountryCode,tTRtype,tTRtrainStopping,tTRcommercialStop,tTRcancelled,tTRscheduledTime,tTRactualTime,tTRdifferenceInMinutes,tTRcauses,tTRcommercialTrack,tTRtrainReady.source,tTRtrainReady.accepted,tTRtrainReady.timestamp,tTRestimateSource,tTRliveEstimateTime,trainNumber,departureDate,trainType
0,HKI,1,FI,DEPARTURE,True,True,False,2023-10-17T03:55:00.000Z,2023-10-17T03:55:31.000Z,1,[],7,KUPLA,True,2023-10-17T03:52:09.000Z,NaN,NaN,1,2023-10-17,IC
1,PSL,10,FI,ARRIVAL,True,True,False,2023-10-17T04:00:00.000Z,2023-10-17T04:00:02.000Z,0,[],4,NaN,NaN,NaN,NaN,NaN,1,2023-10-17,IC
2,PSL,10,FI,DEPARTURE,True,True,False,2023-10-17T04:01:00.000Z,2023-10-17T04:01:55.000Z,1,[],4,NaN,NaN,NaN,NaN,NaN,1,2023-10-17,IC
3,KÄP,977,FI,ARRIVAL,False,NaN,False,2023-10-17T04:03:00.000Z,2023-10-17T04:04:14.000Z,1,[],,NaN,NaN,NaN,NaN,NaN,1,2023-10-17,IC
4,KÄP,977,FI,DEPARTURE,False,NaN,False,2023-10-17T04:03:00.000Z,2023-10-17T04:04:14.000Z,1,[],,NaN,NaN,NaN,NaN,NaN,1,2023-10-17,IC