# Data Analytics - Exercise 1

The assignment file must be submitted as an HTML file (not as an ipynb file), showing **both the contents of the code cells and the outputs.** You can convert the notebook to an HTML file by selecting File -> Download as -> HTML. Submit the assignment file in this exercise and check your assignment using the automatic checking in Moodle.

**Student Name**: Jayani Kothalawala

**Student Number**: AD9680

## Pandas Series - selecting values, descriptive statistics and filtering

In the next cell, a Pandas series from the list "severity_level" has been created. The index labels have been set to dates with times.

a) Select the last two values from the series using index numbers.

b) Select the values from the series for the time interval 2024-01-02 08:00:00 - 2024-01-02 11:00:00 using index labels.

c) What unique values appear in the series? (Print out all the unique values)

d) Select all rows where the value is "High".

e) How many "High" or "Medium" values are there in the series?

Scoring: 0.5 points for each part, total 2.5 points.

In [257]:
import pandas as pd

# A list of data
severity_level = ['Low', 'Low', 'Low', 'Medium', 'Low', 'Medium', 'High', 'High', 'High', 'Medium', 'Medium', 'Low', 'Medium', 'Low', 'High',
       'Medium', 'High', 'Low', 'High']

# Creating indexes
indexes = pd.date_range(start='1/2/2024', freq='H', periods=19)

# Creating a series
ser = pd.Series(data=severity_level, index=indexes)

C:\Users\jayan\AppData\Local\Temp\ipykernel_46236\2793000326.py:8: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  indexes = pd.date_range(start='1/2/2024', freq='H', periods=19)

In [258]:
# Cell /solution 1.1 a)
# Select the last two values from the series using index numbers. Copy and paste the whole output to Moodle's automatic reviewing.

ser.tail(2)

2024-01-02 17:00:00     Low
2024-01-02 18:00:00    High
Freq: h, dtype: object

In [259]:
# Cell /answer 1.1 b)
# Select values from the series for the time interval 2024-01-02 08:00:00 - 2024-01-02 11:00:00 using index labels.

ser['2024-01-02 08:00:00':'2024-01-02 11:00:00']

2024-01-02 08:00:00      High
2024-01-02 09:00:00    Medium
2024-01-02 10:00:00    Medium
2024-01-02 11:00:00       Low
Freq: h, dtype: object

In [260]:
# Cell /answer 1.1 c)
# What unique values appear in the series? (Print out all the unique values that the series contains). Find out the function specific function that you can use to print out unique values.
ser.unique()

array(['Low', 'Medium', 'High'], dtype=object)

In [261]:
# Cell /answer 1.1 d)
# Select all rows where the value is "High".
ser[ser == 'High']

2024-01-02 06:00:00    High
2024-01-02 07:00:00    High
2024-01-02 08:00:00    High
2024-01-02 14:00:00    High
2024-01-02 16:00:00    High
2024-01-02 18:00:00    High
dtype: object

In [262]:
# Cell /answer 1.1 e)
# How many "High" or "Medium" values are there in the series?
se = ser[ser.isin(['High', 'Medium'])].count()
print(se)

12

## Pandas Series - descriptive statistecs and filtering continued...

Below are two lists, where the list "anomaly_score" contains the numerical value of network traffic anomalies. The list "severity_level" classifies the values of the "anomaly_score" list into three categories: 'Low', 'Medium', and 'High', which describe the level of traffic anomaly. Create two Series from the lists (named, for example, sl and ans). You can think of having two columns of a table, from which you can filter data using only one column or both columns. Determine the following by filtering and using built-in functions:

a) How many elements in the Anomaly Scores series are over 50?

b) How many elements have an Anomaly Score over 50 and a Severity Level of "High" or "Medium"?

c) What is the average value of the Anomaly Scores?

d) What is the maximum value of the non-"High" values (sl is not "High")?

e) Select the first 3 characters of the values at indices 3 and 4 in the Severity Level series. Note that indexing starts at zero.

Avoid using for-functions, use slicing instead!

Scoring: 0.5 points for each part, total 2.5 points.

In [263]:
anomaly_scores = [28.67, 51.5 , 87.42, 15.79,  0.52,  5.76, 31.55, 54.05, 56.34,
       16.51, 24.91, 86.07, 74.2 , 62.14, 72.65, 91.56, 43.83, 40.46, 44.75]

severity_level = ['Low', 'Low', 'Low', 'Medium', 'Low', 'Medium', 'High', 'High', 'High', 'Medium', 'Medium', 'Low', 'Medium', 'Low', 'High',
       'Medium', 'High', 'Low', 'High']

sl = pd.Series(severity_level) # Severity Level -series
ans = pd.Series(anomaly_scores) # Anomaly Scores -series

In [264]:
# Cell / answer 1.2 a)
# How many elements in the Anomaly Scores series are over 50?
an = ans[ans > 50].count()
print(an)

9

In [265]:
# Cell / answer 1.2 b)
# How many elements have an Anomaly Score over 50 and a Severity Level of "High" or "Medium"?
anse = ans[(ans > 50) & (sl.isin(['High', 'Medium']))].count()
print(anse)

5

In [266]:
# Cell / answer 1.2 c)
# What is the average value of the Anomaly Scores? Use a in-build function to determine the average.
avg = ans.mean()
print(avg)

46.772631578947376

In [267]:
# Cell / answer 1.2 d)
# What is the maximum value of the non-"High" values (sl is not "High")? Use the combination of filtering and in-build functions.
ans[sl != "High"].max()

91.56

In [268]:
# Cell / answer 1.2 e)
# Select the first 3 characters of the values at indices 3 and 4 in the Severity Level series. Note that indexing starts at zero. Slice first and then select first values in strings.
sl[3:5].str[:3]

3    Med
4    Low
dtype: object

## Creating a DataFrame and Filtering Values
Below is a dictionary (d) that contains network traffic data and timestamps in the list "Timestamps".

a) Create a DataFrame from the dictionary, setting the timestamps as the indices. The dictionary keys, "Source IP Address", "Destination IP Address", "Source Port", "Destination Port", and "Protocol" will become the column headers. Print the first 2 rows of the created DataFrame.

b) Filter the DataFrame to include only the rows where the value in the Protocol column is "TCP" and the beginning part of the Source IP Address column (before the first dot) is 104. (Hint: split)

Scoring: a) 0.5 points, b) 0.5 points, total 1 points.

In [269]:
d = {'Source IP Address': ['103.216.15.12', '78.199.217.198', '63.79.210.48', '163.42.196.10', '71.166.185.76', '198.102.5.160', '97.253.103.59', '11.48.99.245', '49.32.208.167', '114.109.149.113', '177.21.83.200', '92.4.25.171', '57.91.207.84', '80.28.21.123', '54.163.130.178', '130.163.192.252', '4.255.187.165', '212.164.196.41', '119.101.120.119', '104.176.150.78', '116.61.253.182', '214.247.90.42', '57.7.171.107', '46.236.76.78', '71.41.31.239', '128.47.86.24', '182.232.245.98', '208.44.127.159', '197.137.61.248', '69.60.34.24'],
     'Destination IP Address': ['84.9.164.252', '66.191.137.154', '198.219.82.17', '101.228.192.255', '189.243.174.238', '147.190.155.133', '77.16.101.53', '178.157.14.116', '72.202.237.9', '160.88.194.172', '196.218.124.169', '112.43.185.24', '98.96.110.38', '111.204.103.106', '62.112.149.214', '12.192.2.112', '136.159.186.239', '32.26.31.49', '47.125.34.52', '110.80.185.102', '170.92.148.90', '196.26.121.164', '76.146.23.52', '68.194.124.162', '105.193.254.47', '9.149.23.14', '153.211.183.215', '121.167.40.167', '87.49.219.65', '160.208.108.125'],
     'Source Port': [31225, 17245, 16811, 20018,  6131, 17430, 26562, 34489, 56296, 37918, 35538, 10903, 53471, 43729, 47795, 24912, 39934, 16513, 4510, 55147, 24907, 37998,  3133, 40832, 39911, 23021, 32552, 56607, 64351, 19954],
     'Destination Port': [17616, 48166, 53600, 32534, 26646, 52805, 17416, 20396, 20857, 50039, 35006, 36817, 38048, 10845, 35243, 21176,  5259, 50583, 26783, 17595, 37634,  1757, 46077, 28015, 27107, 31279, 15521, 33023, 43307, 11594],
     'Protocol': ['ICMP', 'ICMP', 'UDP', 'UDP', 'TCP', 'UDP', 'TCP', 'ICMP', 'TCP', 'UDP', 'ICMP', 'TCP', 'ICMP', 'ICMP', 'UDP', 'TCP', 'TCP', 'TCP', 'TCP', 'TCP', 'ICMP', 'UDP', 'UDP', 'UDP', 'TCP', 'UDP', 'UDP', 'TCP', 'ICMP', 'UDP']
    }

Timestamps = ['2023-05-30 06:33:58', '2020-08-26 07:08:30', '2022-11-13 08:23:25', '2023-07-02 10:38:46', '2023-07-16 13:11:07', '2022-10-28 13:14:27', '2022-05-16 17:55:43', '2023-02-12 07:13:17', '2023-06-27 11:02:56', '2021-08-15 22:29:04', '2022-07-20 13:28:50', '2022-06-26 15:15:50', '2020-09-30 21:35:31', '2021-01-13 02:30:18', '2023-02-01 13:17:17', '2023-09-15 20:35:21', '2023-04-18 16:46:46', '2023-02-21 07:02:55', '2020-12-29 02:50:47', '2020-07-27 00:00:53', '2021-07-16 20:45:42', '2022-04-29 14:46:46', '2023-02-24 06:39:25', '2023-09-15 15:43:03', '2023-10-06 06:53:51', '2023-10-06 02:37:35', '2021-01-31 03:12:04', '2020-08-28 09:54:45', '2021-05-29 15:33:51', '2022-05-30 18:26:12']

In [276]:
# Cell / answer 1.3 a)
# Create a DataFrame from the dictionary, setting the timestamps as the indices.
pd.DataFrame(data=d, index=Timestamps)

,Source IP Address,Destination IP Address,Source Port,Destination Port,Protocol
2023-05-30 06:33:58,103.216.15.12,84.9.164.252,31225,17616,ICMP
2020-08-26 07:08:30,78.199.217.198,66.191.137.154,17245,48166,ICMP
2022-11-13 08:23:25,63.79.210.48,198.219.82.17,16811,53600,UDP
2023-07-02 10:38:46,163.42.196.10,101.228.192.255,20018,32534,UDP
2023-07-16 13:11:07,71.166.185.76,189.243.174.238,6131,26646,TCP
2022-10-28 13:14:27,198.102.5.160,147.190.155.133,17430,52805,UDP
2022-05-16 17:55:43,97.253.103.59,77.16.101.53,26562,17416,TCP
2023-02-12 07:13:17,11.48.99.245,178.157.14.116,34489,20396,ICMP
2023-06-27 11:02:56,49.32.208.167,72.202.237.9,56296,20857,TCP
2021-08-15 22:29:04,114.109.149.113,160.88.194.172,37918,50039,UDP
2022-07-20 13:28:50,177.21.83.200,196.218.124.169,35538,35006,ICMP
2022-06-26 15:15:50,92.4.25.171,112.43.185.24,10903,36817,TCP
2020-09-30 21:35:31,57.91.207.84,98.96.110.38,53471,38048,ICMP
2021-01-13 02:30:18,80.28.21.123,111.204.103.106,43729,10845,ICMP
2023-02-01 13:17:17,54.163.130.178,62.112.149.214,47795,35243,UDP
2023-09-15 20:35:21,130.163.192.252,12.192.2.112,24912,21176,TCP
2023-04-18 16:46:46,4.255.187.165,136.159.186.239,39934,5259,TCP
2023-02-21 07:02:55,212.164.196.41,32.26.31.49,16513,50583,TCP
2020-12-29 02:50:47,119.101.120.119,47.125.34.52,4510,26783,TCP
2020-07-27 00:00:53,104.176.150.78,110.80.185.102,55147,17595,TCP
2021-07-16 20:45:42,116.61.253.182,170.92.148.90,24907,37634,ICMP
2022-04-29 14:46:46,214.247.90.42,196.26.121.164,37998,1757,UDP
2023-02-24 06:39:25,57.7.171.107,76.146.23.52,3133,46077,UDP
2023-09-15 15:43:03,46.236.76.78,68.194.124.162,40832,28015,UDP
2023-10-06 06:53:51,71.41.31.239,105.193.254.47,39911,27107,TCP
2023-10-06 02:37:35,128.47.86.24,9.149.23.14,23021,31279,UDP
2021-01-31 03:12:04,182.232.245.98,153.211.183.215,32552,15521,UDP
2020-08-28 09:54:45,208.44.127.159,121.167.40.167,56607,33023,TCP
2021-05-29 15:33:51,197.137.61.248,87.49.219.65,64351,43307,ICMP
2022-05-30 18:26:12,69.60.34.24,160.208.108.125,19954,11594,UDP

In [271]:
# Cell / answer 1.3 b)
# Filter the DataFrame to include only the rows where the value in the Protocol column is "TCP" and the beginning part of the Source IP Address column (before the first dot) is 104. (Hint: split)
df[(df["Protocol"] == "TCP") & (df["Source IP Address"].str.split(".").str[0] == "104")]

,Source IP Address,Destination IP Address,Source Port,Destination Port,Protocol
2020-07-27 00:00:53,104.176.150.78,110.80.185.102,55147,17595,TCP