# Data Analytics - Exercise 5

Note that the tasks should be submitted as an HTML file, showing both the contents of the code cells and the outputs. You can get the notebook as an HTML file by selecting File -> Download as -> HTML. The answers to the tasks can be done in one or more code cells.

**Student's Name**: Jayani Kothalawala

**Student Number**: AD9680

## Timestamps - Part 1

In Exercise 2, Task 1.4, we practiced reading data from a text file (apache_log.txt). Due to the formatting in the read data, the timestamps were not directly placed in the same column and in the desired format. In this task, we will continue handling the timestamp from the read data.

a) Read the data either in the same way as in Exercise 2 or, if you were unable to read the data from the text file, you can read it as a CSV from the following URL. The initial situation is as shown in the model below:

![malli_apache1](https://student.labranet.jamk.fi/~ajota/Data-analytics/images/malli_apache_log_times_gmt_sep.png)

b) Remove the square brackets from the data in the "Timestamp" and "zone" columns, and combine the data from these columns into a single column "Timestamp + zone" (Do not add a space between the timestamp and timezone information).

c) Drop the old 'Timestamp' and 'zone' columns.

d) Convert the data in the "Timestamp + zone" column to Timestamp objects, utc=False.

e) Using the "Timestamp + zone" column, create a new "Timestamp (utc)" column where the timestamps are in UTC time (Timestamp objects).

Scoring: 2 p

In [262]:
import pandas as pd

In [263]:
# Cell / answer 1.1 a)-b)
# Copy the first row to Moodle.
df = pd.read_csv('https://student.labranet.jamk.fi/~ajota/Datasets/apache_log_as_csv.csv', index_col=0)

# Write the code here...
df["zone"] = df["zone"].str.strip("[]")
df["Timestamp"] = df["Timestamp"].str.strip("[]")
df['Timestamp + zone'] = df['Timestamp'] + df['zone']

# Drop old columns
df = df.drop(columns=['Timestamp', 'zone'])


# Copy the whole row with it's column header and all to Moodle.
df.head(1)

,Client's IP address,Identd,Userid,Request line from the client,Status code,Size of content,Referer,User-Agent HTTP request header,Timestamp + zone
0,109.169.248.247,-,-,GET /administrator/ HTTP/1.1,200,4263,-,Mozilla/5.0 (Windows NT 6.0; rv:34.0) Gecko/20...,12/Dec/2015:18:25:11+0100

In [264]:
# Cell / answer 1.1 d)

# Write the code below...

df['Timestamp + zone'] = pd.to_datetime(df['Timestamp + zone'], format="%d/%b/%Y:%H:%M:%S%z", utc=False)
# Leave this last and copy the output to Moodle.
df['Timestamp + zone'][0]

Timestamp('2015-12-12 18:25:11+0100', tz='UTC+01:00')

In [265]:
# Cell / answer 1.1 e)

# Write the code below...
df["Timestamp (utc)"] = pd.to_datetime(df['Timestamp + zone'], format="%d/%b/%Y:%H:%M:%S%z", utc=True)

# Leave this last and copy the output to Moodle.
df['Timestamp (utc)'][0]

Timestamp('2015-12-12 17:25:11+0000', tz='UTC')

## Timestamps - Part 2


Sometimes, datasets represent time as Unix timestamps, where time is given in seconds since January 1, 1970, 00:00:00 UTC.

The goal of this exercise is to learn how to convert Unix time to Pandas Timestamp for easier readability and handling.

a) Read the 'normal_traffic_unsw_nb15.csv' data into a dataframe from the address
'https://student.labranet.jamk.fi/~ajota/Datasets/normal_traffic_unsw_nb15.csv'.

b) The data columns contain the information 'record start time'. Create a new column 'Timestamp', where the 'record start time' column is converted from Unix time to Pandas Timestamp. At this stage, make the timestamps tz-naive. Do not add timezone information yet. Sort the dataframe by timestamp in ascending order (the earliest timestamp first), use inplace=True for sorting, and reset the index. Print the first entry of the column.

c) Create new columns 'Year', 'Month', 'Day', and 'Hour', where you extract the corresponding year, month, day, and hour information from the 'Timestamp' column. (Note that the 'Timestamp' column data are (or should be!) Pandas Timestamp objects. Check the Pandas documentation to see what attributes the Timestamp object has to easily create the new columns.) Print the 'Timestamp', 'Year', 'Month', 'Day', and 'Hour' information from the first row of the dataframe.

d) Create a new column 'Timestamp Canberra', where the 'Timestamp' column data are localized to the Australian Canberra timezone.

e) Create a new column 'Timestamp Helsinki', where the 'Timestamp Canberra' column data are converted to the Helsinki timezone.

f) Use the Hour column to calculate which hour has the fewest rows/entries in the data.

Scoring: 3 p

In [266]:
# Reading of the data
dfn = pd.read_csv('https://student.labranet.jamk.fi/~ajota/Datasets/normal_traffic_unsw_nb15.csv', index_col=0)
dfn

,Source IP address,Source port number,Destination IP address,Destination port number,Transaction protocol,"Indicates to the state and its dependent protocol, e.g. ACC, CLO, CON, ECO, ECR, FIN, INT, MAS, PAR, REQ, RST, TST, TXD, URH, URN, and (-) (if not used state)",Record total duration,Source to destination transaction bytes,Destination to source transaction bytes,Source to destination time to live value,...,No of flows that has a command in ftp session.,No. of connections that contain the same service (14) and source address (1) in 100 connections according to the last time (26).,No. of connections that contain the same service (14) and destination address (3) in 100 connections according to the last time (26).,No. of connections of the same destination address (3) in 100 connections according to the last time (26).,No. of connections of the same source address (1) in 100 connections according to the last time (26).,No of connections of the same source address (1) and the destination port (4) in 100 connections according to the last time (26).,No of connections of the same destination address (3) and the source port (2) in 100 connections according to the last time (26).,No of connections of the same source (1) and the destination (3) address in in 100 connections according to the last time (26).,"The name of each attack category. In this data set , nine categories e.g. Fuzzers, Analysis, Backdoors, DoS Exploits, Generic, Reconnaissance, Shellcode and Worms",0 for normal and 1 for attack records
0,59.166.0.3,21779,149.171.126.8,80,tcp,FIN,1.226232,1684,10168,31,...,0,2,2,4,3,1,1,1,NaN,0
1,59.166.0.6,26712,149.171.126.1,111,udp,CON,0.004906,568,320,31,...,0,10,11,4,7,2,1,3,NaN,0
2,59.166.0.5,53035,149.171.126.1,6881,tcp,FIN,0.904841,1540,1644,31,...,0,14,5,5,7,5,1,5,NaN,0
3,59.166.0.2,62778,149.171.126.1,5190,tcp,FIN,0.005624,2048,2410,31,...,0,10,10,3,5,2,2,2,NaN,0
4,59.166.0.2,53340,149.171.126.9,22,tcp,FIN,4.463027,48256,85658,31,...,0,17,5,1,3,1,1,1,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1162,59.166.0.6,58299,149.171.126.7,53,udp,CON,0.001014,130,162,31,...,0,1,1,3,8,1,1,2,NaN,0
1163,59.166.0.8,45922,149.171.126.0,25,tcp,FIN,0.998812,37232,3172,31,...,0,2,1,5,4,2,1,1,NaN,0
1164,59.166.0.0,62426,149.171.126.9,53,udp,CON,0.001049,146,178,31,...,0,3,4,2,1,1,1,1,NaN,0
1165,59.166.0.1,8867,149.171.126.0,42685,tcp,FIN,0.018659,2974,33550,31,...,0,10,7,4,2,1,1,1,NaN,0
1166,59.166.0.4,41801,149.171.126.5,53,udp,CON,0.001064,130,162,31,...,0,4,2,2,5,3,1,1,NaN,0

In [267]:
# Cell / answer 1.2 b)
import pandas as pd
# Write the code below...

dfn["Timestamp"] = pd.to_datetime(dfn["record start time"],unit="s",origin="unix")

dfn.sort_values(by="Timestamp",ascending=True,inplace=True)
dfn.reset_index(inplace=True)
# Leave this last and copy the output to Moodle.
dfn['Timestamp'][0]

Timestamp('2015-01-22 11:50:43')

In [268]:
# Cell / answer 1.2 c)

# Write the code below...
dfn["Year"] = dfn["Timestamp"].dt.year
dfn["Month"] = dfn["Timestamp"].dt.month
dfn["Day"] = dfn["Timestamp"].dt.day
dfn["Hour"] = dfn["Timestamp"].dt.hour
dfn[['Timestamp', 'Year', 'Month', 'Day', 'Hour']].head(1)
# Leave this last and copy the output to Moodle.

            Timestamp  Year  Month  Day  Hour
0 2015-01-22 11:50:43  2015      1   22    11

In [269]:
# Cell / answer 1.2 d)


# Write the code below...
dfn['Timestamp Canberra'] = dfn["Timestamp"].dt.tz_localize(tz="Australia/Canberra")

# Leave this last and copy the output to Moodle.
dfn['Timestamp Canberra'][0]

Timestamp('2015-01-22 11:50:43+1100', tz='Australia/Canberra')

In [270]:
# Cell / answer 1.2 e)

# Write the code below...
dfn['Timestamp Helsinki'] = dfn["Timestamp Canberra"].dt.tz_convert(tz="Europe/Helsinki")


# Leave this last and copy the output to Moodle.
dfn['Timestamp Helsinki'][0]

Timestamp('2015-01-22 02:50:43+0200', tz='Europe/Helsinki')

In [271]:
# Cell / answer 1.2 f)
# Which hour has the fewest records? Write the corresponding hour to Moodle.
dfn["Hour"].value_counts().sort_values(ascending=True)
# 11

Hour
11     21
19     78
18    107
13    134
14    146
17    146
12    148
15    156
16    231
Name: count, dtype: int64

## Timestamps - Part 3

In the following tasks, we will use the data from the previous section. Find the answers to the following questions by resampling the data.

a) From which IP address were there the most connections on an hourly basis?

b) When does the data show the most connections (rows) when viewed in 30-minute intervals? Use the 'Timestamp' column and the resample function to find this information.

Scoring: 1 p

In [272]:
# Cell / answer 1.3 a)
# Write in Moodle the 'Source IP address' from which there have been the most connections on an hourly basis.
dfn["Hour"] = dfn["Timestamp"].dt.floor("h")
res = dfn.groupby(["Hour","Source IP address"]).size().reset_index(name="connections")
res = res.loc[res.groupby("Hour")["connections"].idxmax()]
res.sort_values("connections")

                   Hour Source IP address  connections
1   2015-01-22 11:00:00        59.166.0.0            7
92  2015-01-22 18:00:00        59.166.0.2           14
107 2015-01-22 19:00:00        59.166.0.5           15
36  2015-01-22 13:00:00        59.166.0.6           18
82  2015-01-22 17:00:00        59.166.0.3           19
25  2015-01-22 12:00:00        59.166.0.9           20
59  2015-01-22 15:00:00        59.166.0.6           26
40  2015-01-22 14:00:00        59.166.0.0           28
74  2015-01-22 16:00:00        59.166.0.8           32

In [273]:
# Cell / answer 1.3 b)
# Write in Moodle the timestamp when there were the most connections. (In fact, it is a time interval, from which only the first value of the interval is shown in the summary. Sampled at 30-minute intervals, the first times are 2015-01-22 11:30:00, 2015-01-22 12:00:00, 2015-01-22 12:30:00, ...)
dfn = dfn.set_index("Timestamp")
resampled = dfn.resample("30min").size()
resampled.idxmax()

Timestamp('2015-01-22 16:30:00')